outline for menu prompt
QualityError/TeamVoid-UVSim pull request #74
Opened 2022-07-12 00:41 UTC by QualityError

2022-07-12 00:46 UTC, jansenfuller requested changes

2022-07-12 00:46 UTC, jansenfuller commented on main.cpp
> +    int choice = promptMenu("string", options);
What about if the user doesn't pick an option that doesn't exist?

2022-07-12 00:46 UTC, jansenfuller commented on main.cpp
> +int promptMenu(const char* question, const char* options[]){
Why have a prompt menu when we can cout the stuff we need?

2022-07-12 00:46 UTC, jansenfuller commented on main.cpp
> +    int input;
What's with the new input?

2022-07-12 00:47 UTC, QualityError commented on main.cpp
> +    int choice = promptMenu("string", options);
I plan on adding validation in the prompt menu function for the users input

2022-07-12 00:51 UTC, QualityError commented on main.cpp
> +int promptMenu(const char* question, const char* options[]){
so that as we have several menus we don't want to replicate logic

ideal
have a function for each menu that contains only the definition of the options and a switch statement to make calls based on result of promptMenu() call.

This will allow easy editing and combining of menus to each others

2022-07-12 00:57 UTC, QualityError commented on main.cpp
> +    int input;
it is needed for the user input loop. I moved it from the main method with the rest of the input stuffs

2022-07-16 00:15 UTC, pidoshva approved these changes

2022-07-16 00:31 UTC, merged